### ISSUE TITLE
In table A.2, missing a separator line before VEC_SEL

### ISSUE THREAD

**Issue by cjashfor** [OpenPOWERFoundation/ELFv2-ABI#105]
In the description of the VEC_SEL group, the right side has a function prototype for the previous group: VEC_RSQRTE.  So there's just a missing horizontal separator there.

![image](https://user-images.githubusercontent.com/990065/80528162-5d0deb80-894a-11ea-9814-8a137307b1a9.png)

**Comment by wschmidt-ibm** [comment]
Pretty weird.  Is this the HTML rendering?  The PDF has the missing horizontal separator; looks like an artifact of the HTML engine.

In any case, this table will be deleted in the next version of the ABI (moving to the Power Vector Intrinsics Programming Reference), so we won't make any changes here.  PVIPR doesn't have this artifact.

**Comment by cjashfor** [comment]
That is from the pdf file.  I am viewing it with evince.

**Comment by wschmidt-ibm** [comment]
OK, probably a problem with evince, then.  My dog-eared copy (printed from Adobe) has the separator...

**Comment by cjashfor** [comment]
You're right.  I just viewed it in Libre Office and it looks fine there.  Lesson learned.  Sorry for the noise :/
