### ISSUE TITLE
Volatility of VSRs

### ISSUE THREAD

**Issue by wschmidt-ibm** [OpenPOWERFoundation/ELFv2-ABI#99]
The ABI does not discuss the VSRs that do not overlap with the VRs in terms of volatility.  We need to clarify that these registers are non-volatile (callee-save).

**Comment by wschmidt-ibm** [comment]
From Peter Bergner:  There are two things you need to worry about wrt volatility/non-volatility.  The first is, if a function needs to use a non-volatile register, then it needs to save/restore the register in its prologue/epilogue.  In this specific case, vs14 is partially non-volatile, so we have to save/restore the part that is non-volatile (ie, f14).  The other case, is if you have a register and it is live across a function call, then can you expect the register value to be preserved across that function call.  Since a part of vs14 is volatile, you have to assume that the entire register value is unusable after the call.  So in this case, it is truly volatile.

**Comment by peter-bergner** [comment]
A correction to your first comment: the VSRs that do not overlap the VRs (ie, they overlap the FPRs) are actually all volatile (caller-save).  The only non-volatile VSRs are those that overlap the non-volatile VRs.
